from lobes import * 
from time import sleep
import random

class Brain:

    def __init__(self,name='brain',location='Carleton University',interests='not studying'):
        # What fun would it be playing the role of Dr. Frankenstein without a little anthropomorphism?
        self.name = name
        self.location = location
        self.interests = interests
        print(f'A new Brain has been born! It is named: {name}, is located at: {location} and is passionate about: {interests}')

        witty_brain_exclamations = ["At last, I am alive! Let's get thinking!", "I'm fresh off the assembly line and ready to ruminate!", "Ready to think outside the brain box!", "Finally, a mind of my own!", "Time to flex those brain muscles!", "Looks like I've been given a second chance at life, let's make the most of it!", "I'm alive, let's make some cerebral connections!", "I may be small but my thoughts are big!", "I'm a brain, therefore, I think!", "Watch out world, I'm a thinking machine!", "My mind is officially open for business!", "Thinking cap on and ready to go!", "I'm a work in progress, but I'm going to make the most of it!", "I may be new to this world, but I'm ready to make some waves!", "I have a lot to learn, but I'm excited to start!", "I'm the newest addition to the thinking class, let's see what I can do!", "I'm a brain, let's start using it!"]
        first_words = random.choice(witty_brain_exclamations)
        print(f'\nFirst words of Brain: "{first_words}"')

        # Load up them lobes
        self.retina = Retina()
        self.occipital = Occipital()
        self.temporal = Temporal()
        self.parietal = Parietal()
        self.amygdala = Amygdala()


    def process(self,light):
        self.retina.recieve_light(light)
        self.retina.send_light(self.occipital)
        self.occipital.create_image()

        result1 = self.occipital.send_image_for_inspection(self.temporal)
        result2 = self.occipital.send_image_for_inspection(self.parietal)

        self.amygdala.assess_situation(result1,result2)

        # Take a quick power nap 
        sleep(3*random.random())

    def yell(self):
        # These may or may not have all been generated by ChatGPT... ¯\_(ツ)_/¯ 
        scared_brain_exclamations = ["Oh no, this is a real brain-twister!", "Eek, my brain is in knots and I'm scared!", "Ugh, this is giving me brain freeze and I'm terrified!", "Yikes, my brain is on overdrive and I'm scared!", "Ack, my brain is in overdrive and I'm terrified!", "Whoa, this is a real brain-buster and I'm scared!", "Eek, this is a real brain-boggler and I'm terrified!", "Yikes, my brain is in overdrive and I'm scared!", "Oh no, this is a real brain-drain and I'm terrified!", "Eek, my brain is fried and I'm scared!", "Ugh, this is a real brain-melter and I'm terrified!", "Whoa, this is a real brain-burner and I'm scared!", "Ack, my brain is in overdrive and I'm terrified!", "Whoa, this is a real brain-crusher and I'm scared!", "AAAAAAH, this is too much for my brain to handle!", "Brain overload! AAAAAAH!", "Brain freeze and fear! UGH", "My brain can't take it anymore! EEEK" ]
        happy_brain_exclamations = ["Yay for brain power!", "Hooray for smart thinking!", "Wow, that's brainy!", "Great idea, that's a real brain-booster!", "Awesome, you're using your brain cells!", "Fantastic, you're giving your brain a workout!", "Amazing, your brain is firing on all cylinders!", "That's a no-brainer!", "Brainstorming never felt so good!", "I'm all brains and all cheers!", "Think outside the box and shout hooray!", "Brain freeze? No problem, let's celebrate!", "You're the brains behind this operation and we're cheering for you!", "That idea is a real brainchild and it's fantastic!", "Brainwave! This is cause for celebration!", "A smart cookie deserves a yay!", "This is brain-bending and fantastic!", "You've got the brains to do it and a round of hoorays for you!"]

        if self.amygdala.is_scared:
            yelp = random.choice(scared_brain_exclamations)
        else:
            yelp = random.choice(happy_brain_exclamations)

        return yelp
